version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "maven"
      include: "scope"
    reviewers:
      - "Rume7"
    assignees:
      - "Rume7"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "github-actions"
    reviewers:
      - "Rume7"
    assignees:
      - "Rume7" 