spring:
  application:
    name: EssayGenerationService
  datasource:
    url: ${app.db.url}
    username: ${app.db.username}
    password: ${app.db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

# Application configuration
app:
  db:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  openai:
    api-key: ${OPENAI_API_KEY}
    model: ${OPENAI_MODEL:-gpt-4}
  anthropic:
    api-key: ${ANTHROPIC_API_KEY}
    model: ${ANTHROPIC_MODEL:-claude-3}

# Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
