name: CI and Security

on:
  push:
    branches: [ main, 'feature/**', 'bugfix/**' ]
  pull_request:
    branches: [ main, 'feature/**', 'bugfix/**' ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Checkstyle (Linting)
        run: mvn checkstyle:check --file pom.xml

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Set Docker Image Tag
        id: set_tag # Give this step an ID so we can reference its outputs
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/postgen:${{ env.IMAGE_TAG }}

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Image to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/postgen:${{ env.IMAGE_TAG }}